### ISSUE TITLE
Move from "DefaultService" model to "Dao" model

### ISSUE THREAD

**Issue by krico** [krico/jas#514]
This story centralizes the work related to performance and reducing cost of appengine.  We are replacing `Datastore` direct queries with Dao's which use `Memcache` to acheive better performance.

We will introduce a Dao for each *core* entity, namely:

 - [ ] [activity](jas#509) - ActivityType, Activity, ActivityPackage, ...
 - [ ] [balance](jas#510) - Account, Transaction, Transfer, ...
 - [ ] [common](jas#511) - Group, Organization
 - [ ] [payment](jas#512) - Payment, etc
 - [ ] [users](jas#513) - User, UserLogin, UserDetail, ...
